<?php

namespace Tests\Feature;

use App\Models\User;
use App\Repository\Eloquent\UserRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LoanControllerTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User([
            'name' => 'Igor',
            'email' => 'igor@g.c',
            'password' => '1111Ij!'
        ]);
    }

    public function test_all()
    {
        $this->json('GET', 'api/en/allLoans')
            ->assertStatus(401)
            ->assertJson([
                'error' => "Unauthorized"
            ]);

        $this->actingAs($this->user)->json('GET', 'api/en/allLoans')
            ->assertStatus(200)
            ->assertJsonFragment([
                'status' => 'success'
            ]);
    }

    public function test_accept()
    {
        $data = [
            'sum' => 120
        ];
        $this->json('POST', 'api/en/acceptLoan/1', $data)
            ->assertStatus(200)
            ->assertJson([
                'error' => "Unauthorized"
            ]);
        $this->actingAs($this->user)->json('POST', 'api/en/acceptLoan/1', $data)
            ->assertStatus(200)
            ->assertJson([
                'response' => "Done!"
            ]);
    }
}
