<?php

namespace Tests\Unit\Repositories;

use App\Models\ActiveLoan;
use App\Models\Card;
use App\Models\CardTransfer;
use App\Models\Loan;
use App\Repository\Eloquent\ActiveLoanRepository;
use App\Repository\Eloquent\CardRepository;
use App\Repository\Eloquent\LoanRepository;
use App\Repository\Eloquent\TransferRepository;
use Illuminate\Support\Arr;
use Tests\TestCase;

class ActiveLoanRepositoryTest extends TestCase
{
    /**
     * @var ActiveLoanRepository
     */
    private $activeLoanRepository, $loanRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->activeLoanRepository = new ActiveLoanRepository(
            new ActiveLoan(),
            new CardRepository(new Card()),
            new TransferRepository(new CardTransfer())
        );
        $this->loanRepository = new LoanRepository(
            new Loan(),
            new CardRepository(new Card()),
            new ActiveLoan()
        );
    }

    /**
     * Getting all fields of ActiveLoan
     */
    public function testAll(): void
    {
        $this->assertEquals(ActiveLoan::all(), $this->activeLoanRepository->all());
    }

    /**
     * Getting cardsId from all active loans
     */
    public function testGetCardsId(): void
    {
        $cards = $this->activeLoanRepository->getCardsId();
        $this->assertCount(count(ActiveLoan::all()), $cards);
    }

    /**
     * Decrease loan sum
     */
    public function testDecrease(): void
    {
        $this->loanRepository->newLoan(1, 250, 2, 0);
        $loan = ActiveLoan::where('loan_id', 1)->where('sum', 250)->where('card_id', 2)->first();
        $this->assertTrue($this->activeLoanRepository->decrease([$loan]));
        $this->activeLoanRepository->delete(Arr::get($loan, 'id', null));

        $this->loanRepository->newLoan(4, 250, 3, 0);
        ActiveLoan::where('loan_id', 4)->where('sum', 250)->where('card_id', 3)->update(['month_left' => 0]);
        $loan = ActiveLoan::where('loan_id', 4)->where('sum', 250)->where('card_id', 3)->first();
        $this->assertTrue($this->activeLoanRepository->decrease([$loan]));
    }

    /**
     * Deleting active loan
     */
    public function testDelete(): void
    {
        $this->loanRepository->newLoan(2, 300, 3, 0);
        $loan = ActiveLoan::where('loan_id', 2)->where('sum', 300)->where('card_id', 3)->first();
        $this->assertTrue($this->activeLoanRepository->delete(Arr::get($loan, 'id', null)));
        CardTransfer::where('user_id', 0)->delete();
    }

    /**
     * Checking user loans
     */
    public function testUserLoans(): void
    {
        $this->assertIsObject($this->activeLoanRepository->userLoans(1));
    }

}
