<?php

namespace Tests\Unit\Repositories;

use App\Models\ActiveLoan;
use App\Models\Card;
use App\Models\CardTransfer;
use App\Models\Loan;
use App\Repository\Eloquent\ActiveLoanRepository;
use App\Repository\Eloquent\CardRepository;
use App\Repository\Eloquent\LoanRepository;
use App\Repository\Eloquent\TransferRepository;
use Database\Seeders\ActiveLoanSeeder;
use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Tests\TestCase;

class ActiveLoanRepositoryTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var ActiveLoanRepository
     */
    private $activeLoanRepository, $loanRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(UserSeeder::class);
        $this->seed(ActiveLoanSeeder::class);

        $this->activeLoanRepository = new ActiveLoanRepository(
            new ActiveLoan(),
        );
        $this->loanRepository = new LoanRepository(
            new Loan(),
            new ActiveLoan()
        );
    }

    /**
     * Getting all fields of ActiveLoan
     */
    public function testAll(): void
    {
        $loans = $this->activeLoanRepository->all();
        $this->assertCount(1, $loans);
        $oneLoan = Arr::get($loans, 0, null);
        $this->assertEquals(1200, Arr::get($oneLoan, 'sum', 0));
    }

    /**
     * Getting cardsId from all active loans
     */
    public function testGetCardsId(): void
    {
        $cards = $this->activeLoanRepository->getCardsId();
        $this->assertCount(1, $cards);
    }

    /**
     * Checking loan by current date
     */
    public function testGetLoansByDate(): void
    {
        $loans = $this->activeLoanRepository->getLoansByDate();
        $this->assertCount(1, $loans);
    }

    /**
     * Deleting active loan
     */
    public function testDelete(): void
    {

        $this->assertTrue($this->activeLoanRepository->delete());
    }

    /**
     * Checking user loans
     */
    public function testUserLoans(): void
    {
        $this->assertCount(1, $this->activeLoanRepository->userLoans(1));
    }

    /**
     * Getting ids of loans
     */
    public function testGetIds(): void
    {
        $this->assertCount(1, $this->activeLoanRepository->getIds());
    }

    /**
     * Update date of deposit
     */
    public function testUpdateDate(): void
    {
        $date = date('y-m-d');
        $this->activeLoanRepository->updateDate(7, $date);
//        print_r($this->activeLoanRepository->all());
        $this->assertDatabaseHas('active_loans', [
            'created_at' => $date
        ]);
    }
}
