<?php

namespace Tests\Unit\Repositories;

use App\Models\Card;
use App\Repository\Eloquent\CardRepository;
use Tests\TestCase;

class CardRepositoryTest extends TestCase
{
    /**
     * @var CardRepository
     */
    private $cardRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cardRepository = new CardRepository(new Card());
    }

    /**
     * Getting all fields of Card
     */
    public function testAll(): void
    {
        $this->assertEquals(Card::all(), $this->cardRepository->all());
    }

    /**
     * Finding all Cards which Ids in array
     */
    public function testFindAll(): void
    {
        $cards = $this->cardRepository->findAll([10, 11, 20]);
        $this->assertCount(3, $cards);
        $this->assertEquals('2221805713436591', $cards[2]['number']);
    }

    /**
     * Checking if card exists
     */
    public function testCardExist(): void
    {
        $data = array(
            'number' => '0000000000000000',
            'cvv' => '311',
            'expires-end' => date('Y-d-m', mktime(0, 0, 0, 2, 11, 2021))
        );
        $this->assertTrue($this->cardRepository->cardExist($data));
    }

    /**
     * Getting card Id by number
     */
    public function testGetId(): void
    {
        $this->assertEquals(3, $this->cardRepository->getId('0000000000000002'));
    }

    /**
     * Getting card info by number
     */
    public function testGetCardByNum(): void
    {
        $this->assertEquals('general',
            $this->cardRepository->getCardByNum('0000000000000002')['type']);
    }

    /**
     * Getting balance of card by id
     */
    public function testGetSumFrom(): void
    {
        $this->assertEquals(11864, $this->cardRepository->getSumFrom(10));
    }

    /**
     * Getting balance of card by id
     */
    public function testGetSumTo(): void
    {
        $this->assertEquals(11864, $this->cardRepository->getSumTo('5217598081837917'));
    }

    /**
     * Updating card by id
     */
    public function testUpdateFrom(): void
    {
        $sum = $this->cardRepository->getSumFrom(10);
        $this->cardRepository->updateFrom(10, ['sum' => $sum + 1]);
        $this->assertEquals(11865, $this->cardRepository->getSumFrom(10));

        $this->cardRepository->updateFrom(10, ['sum' => $sum]);
        $this->assertEquals(11864, $this->cardRepository->getSumFrom(10));
    }

    /**
     * Updating card by number
     */
    public function testUpdateTo(): void
    {
        $sum = $this->cardRepository->getSumTo('5217598081837917');
        $this->cardRepository->updateTo('5217598081837917', ['sum' => $sum + 1]);
        $this->assertEquals(11865, $this->cardRepository->getSumTo('5217598081837917'));

        $this->cardRepository->updateTo('5217598081837917', ['sum' => $sum]);
        $this->assertEquals(11864, $this->cardRepository->getSumTo('5217598081837917'));
    }

    /**
     * Getting currency of card by id
     */
    public function testGetCurrencyFrom(): void
    {
        $this->assertEquals('UAH', $this->cardRepository->getCurrencyFrom(1));
    }

    /**
     * Getting currency of card by number
     */
    public function testGetCurrencyTo(): void
    {
        $this->assertEquals('EUR', $this->cardRepository->getCurrencyTo('0000000000000001'));
    }

    /**
     * Getting general card number by other card id
     */
    public function testGetGeneralCardNum(): void
    {
        $this->assertEquals('0000000000000002', $this->cardRepository->getGeneralCardNum(10));
    }

    /**
     * Updating balance of card by id
     */
    public function testUpdateSum(): void
    {
        $this->cardRepository->updateSum(11, 20);
        $this->assertEquals(87213.0, $this->cardRepository->getSumFrom(11));

        $sum = $this->cardRepository->getSumFrom(11);
        $this->cardRepository->updateFrom(11, ['sum' => $sum + 20]);
        $this->assertEquals(87233.0, $this->cardRepository->getSumFrom(11));
    }

    /**
     * Finding card number by its id
     */
    public function testGetNumber(): void
    {
        $this->assertEquals('0000000000000000', $this->cardRepository->getNumber(1));
    }

    /**
     * Checking if user has credit card with necessary currency
     */
    public function testCredit(): void
    {
        $this->assertNull($this->cardRepository->credit([1, 2, 3], 1));
    }

    /**
     * Checking finding user cards
     */
    public function testFind(): void
    {
        $this->assertEquals(Card::find(2), $this->cardRepository->find(2));
    }

}
