<?php

namespace Tests\Unit\Repositories;

use App\Models\CardTransfer;
use App\Repository\Eloquent\TransferRepository;
use Tests\TestCase;

class TransferRepositoryTest extends TestCase
{
    /**
     * @var TransferRepository
     */
    private $transferRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->transferRepository = new TransferRepository(new CardTransfer());
    }

    /**
     * Getting all fields of UserCard
     */
    public function testAll(): void
    {
        $this->assertEquals(CardTransfer::all(), $this->transferRepository->all());
    }

    /**
     * Getting all card transfers
     */
    public function testGetCardTransactions(): void
    {
        $this->assertEmpty($this->transferRepository->getCardTransactions(11));
    }

    /**
     * Checking all cards transactions
     */
    public function testAllTransactions(): void
    {
        $this->assertTrue((bool) $this->transferRepository->allTransactions(['0000000000000000', '0000000000000001']));
    }
}
