<?php

namespace Tests\Unit\Repositories;

use App\Models\UserCard;
use App\Repository\Eloquent\UserRepository;
use App\Repository\EloquentRepositoryInterface;
use Tests\TestCase;
use App\Models\User;

class UserRepositoryTest extends TestCase
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRepository = new UserRepository(new User());
    }

    /**
     * Getting all fields of User
     */
    public function testAll(): void
    {
        $this->assertEquals(User::all(), $this->userRepository->all());
    }

    /**
     * Getting all user cards
     */
    public function testGetCards(): void
    {
        $this->assertEquals(UserCard::select('card_id')->where('user_id', 1)->get(),
            $this->userRepository->getCards(1));
    }

    /**
     * Getting username of authenticated user
     */
    public function testGetUsername(): void
    {
        $this->assertEquals('Sasha', $this->userRepository->getUsername('1@2.3'));
    }

}
