<?php

namespace Tests\Unit\Repositories;

use App\Models\UserCard;
use App\Repository\Eloquent\UserRepository;
use App\Repository\EloquentRepositoryInterface;
use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\User;

class UserRepositoryTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(UserSeeder::class);

        $this->userRepository = new UserRepository(new User());
    }

    /**
     * Getting all fields of User
     */
    public function testAll(): void
    {
        $this->assertCount(1, $this->userRepository->all());
    }

    /**
     * Getting all user cards
     */
    public function testGetCards(): void
    {
        $this->assertCount(0, $this->userRepository->getCards(1));
    }

    /**
     * Getting username of authenticated user
     */
    public function testGetUsername(): void
    {
        $this->assertEquals('Igor', $this->userRepository->getUsername('igor@g.c'));
    }

}
