<?php

namespace Tests\Unit\Repositories;

use App\Models\UserCard;
use App\Repository\Eloquent\UserCardRepository;
use Tests\TestCase;

class UserCardRepositoryTest extends TestCase
{
    /**
     * @var UserCardRepository
     */
    private $usercardRepository;

    /**
     * Set up the test environment.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->usercardRepository = new UserCardRepository(new UserCard());
    }

    /**
     * Getting all fields of UserCard
     */
    public function testAll(): void
    {
        $this->assertEquals(UserCard::all(), $this->usercardRepository->all());
    }

    /**
     * Checking of existing card
     */
    public function testCards(): void
    {
        $this->assertFalse($this->usercardRepository->cards(1));
    }

    /**
     * Getting all user cards
     */
    public function testCardIdByUser(): void
    {
        $this->assertEquals('[{"card_id":111},{"card_id":112},{"card_id":8},{"card_id":113}]',
            $this->usercardRepository->cardIdByUser(1));
    }

    /**
     * Creating card for user
     */
    public function testCreateNew(): void
    {
        $this->assertTrue($this->usercardRepository->createNew(1, 1));
        $this->usercardRepository->delete(1, 1);
    }

    /**
     * Deleting card from user
     */
    public function testDelete(): void
    {
        $this->usercardRepository->createNew(1, 1);
        $this->assertTrue($this->usercardRepository->delete(1, 1));
    }
}
